<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InventorySeeder extends Seeder
{
    /**
     * Seed car units and inventory-related logs with 42 realistic vehicles and 126 uniform 16:9 images.
     */
    public function run(): void
    {
        $now = now();

        $trimIds = DB::table('trims')->pluck('id', 'slug');
        $bodyTypeIds = DB::table('body_types')->pluck('id', 'slug');
        $fuelTypeIds = DB::table('fuel_types')->pluck('id', 'slug');
        $transmissionIds = DB::table('transmissions')->pluck('id', 'slug');
        $drivetrainIds = DB::table('drivetrains')->pluck('id', 'slug');
        $colorIds = DB::table('colors')->pluck('id', 'slug');

        $units = [
            // ================= 1. TOYOTA (5 xe) =================
            [
                'stock_code' => 'NEW-CAMRY-001',
                'trim_slug' => 'camry-25hev',
                'condition' => 'new',
                'vin' => 'JTNB11006SL000006',
                'year' => 2025,
                'mileage' => 10,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'hybrid',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-brown',
                'price' => 1495000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(1),
                'sold_at' => null,
                'notes_internal' => 'Phiên bản Camry Hybrid đầu bảng, giao ngay trong tháng.',
            ],
            [
                'stock_code' => 'NEW-VIOS-001',
                'trim_slug' => 'vios-g',
                'condition' => 'new',
                'vin' => 'RLVAB4004SL000004',
                'year' => 2025,
                'mileage' => 25,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'cvt',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-black',
                'price' => 545000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(2),
                'sold_at' => null,
                'notes_internal' => 'Xe mới 100%, sẵn xe giao ngay, tặng gói dán kính cách nhiệt.',
            ],
            [
                'stock_code' => 'USED-CROSS-001',
                'trim_slug' => 'corolla-cross-hybrid',
                'condition' => 'used',
                'vin' => 'JTNGB1002SL000002',
                'year' => 2023,
                'mileage' => 23500,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'hybrid',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-beige',
                'price' => 825000000,
                'currency' => 'VND',
                'status' => 'on_hold',
                'hold_until' => $now->copy()->addDays(2),
                'published_at' => $now->copy()->subDays(20),
                'sold_at' => null,
                'notes_internal' => 'Khách yêu cầu giữ xe trong lúc chờ ngân hàng phê duyệt hồ sơ vay.',
            ],
            [
                'stock_code' => 'CPO-VIOS-001',
                'trim_slug' => 'vios-e',
                'condition' => 'cpo',
                'vin' => 'RLVAB4004SL000019',
                'year' => 2024,
                'mileage' => 12000,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-black',
                'price' => 440000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(4),
                'sold_at' => null,
                'notes_internal' => 'Xe CPO chứng nhận 176 hạng mục chính hãng, tiết kiệm nhiên liệu.',
            ],
            [
                'stock_code' => 'USED-CAMRY-001',
                'trim_slug' => 'camry-20q',
                'condition' => 'used',
                'vin' => 'JTNB11006SL000020',
                'year' => 2023,
                'mileage' => 28000,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-brown',
                'price' => 1150000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(14),
                'sold_at' => null,
                'notes_internal' => 'Camry 2.0Q nhập Thái Lan một đời chủ, dàn âm thanh JBL 9 loa.',
            ],

            // ================= 2. HONDA (5 xe) =================
            [
                'stock_code' => 'NEW-CIVIC-001',
                'trim_slug' => 'civic-rs',
                'condition' => 'new',
                'vin' => 'JHMFC1001SL000001',
                'year' => 2025,
                'mileage' => null,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'cvt',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'candy-red',
                'interior_color_slug' => 'cabin-black',
                'price' => 865000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(3),
                'sold_at' => null,
                'notes_internal' => 'Xe trưng bày showroom, phiên bản thể thao RS cao cấp nhất.',
            ],
            [
                'stock_code' => 'CPO-CITY-001',
                'trim_slug' => 'city-rs',
                'condition' => 'cpo',
                'vin' => 'RLHAB5005SL000005',
                'year' => 2024,
                'mileage' => 9000,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'cvt',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'ocean-blue',
                'interior_color_slug' => 'cabin-black',
                'price' => 585000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(7),
                'sold_at' => null,
                'notes_internal' => 'Xe CPO kèm gia hạn bảo hành chính hãng 1 năm.',
            ],
            [
                'stock_code' => 'NEW-CRV-001',
                'trim_slug' => 'crv-ehev-rs',
                'condition' => 'new',
                'vin' => 'MRHRA7007SL000007',
                'year' => 2025,
                'mileage' => 15,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'hybrid',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-black',
                'price' => 1259000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(4),
                'sold_at' => null,
                'notes_internal' => 'Xe nhập khẩu Thái Lan, động cơ hybrid 204 mã lực bốc và tiết kiệm.',
            ],
            [
                'stock_code' => 'USED-CIVIC-001',
                'trim_slug' => 'civic-g',
                'condition' => 'used',
                'vin' => 'JHMFC1001SL000021',
                'year' => 2023,
                'mileage' => 24000,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'cvt',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-black',
                'price' => 720000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(12),
                'sold_at' => null,
                'notes_internal' => 'Civic bản G động cơ VTEC Turbo 176 mã lực vận hành ổn định.',
            ],
            [
                'stock_code' => 'USED-CRV-001',
                'trim_slug' => 'crv-l-2wd',
                'condition' => 'used',
                'vin' => 'MRHRA7007SL000022',
                'year' => 2023,
                'mileage' => 31000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'cvt',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-black',
                'price' => 990000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(16),
                'sold_at' => null,
                'notes_internal' => 'CR-V 7 chỗ máy 1.5 Turbo gia đình sử dụng kỹ, bảo hiểm 2 chiều còn hạn.',
            ],

            // ================= 3. FORD (5 xe) =================
            [
                'stock_code' => 'USED-RANGER-001',
                'trim_slug' => 'ranger-wildtrak',
                'condition' => 'used',
                'vin' => 'MNBAB3003SL000003',
                'year' => 2022,
                'mileage' => 41000,
                'body_type_slug' => 'pickup',
                'fuel_type_slug' => 'diesel',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => '4wd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-brown',
                'price' => 920000000,
                'currency' => 'VND',
                'status' => 'sold',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(60),
                'sold_at' => $now->copy()->subDays(5),
                'notes_internal' => 'Xe trade-in một đời chủ có lịch sử bảo dưỡng đầy đủ.',
            ],
            [
                'stock_code' => 'CPO-EVEREST-001',
                'trim_slug' => 'everest-titanium-plus',
                'condition' => 'cpo',
                'vin' => 'MNBCR8008SL000008',
                'year' => 2024,
                'mileage' => 16000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'diesel',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => '4wd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-brown',
                'price' => 1390000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(5),
                'sold_at' => null,
                'notes_internal' => 'Bản 2 cầu cao cấp nhất, dẫn động 4 bánh toàn thời gian, camera 360.',
            ],
            [
                'stock_code' => 'USED-TERRITORY-001',
                'trim_slug' => 'territory-titanium-x',
                'condition' => 'used',
                'vin' => 'LVSCR9009SL000009',
                'year' => 2023,
                'mileage' => 28000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-black',
                'price' => 795000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(8),
                'sold_at' => null,
                'notes_internal' => 'Nội thất da hai màu, làm mát ghế, bảo dưỡng định kỳ đầy đủ.',
            ],
            [
                'stock_code' => 'USED-RAPTOR-001',
                'trim_slug' => 'ranger-raptor',
                'condition' => 'used',
                'vin' => 'MNBAB3003SL000023',
                'year' => 2023,
                'mileage' => 19000,
                'body_type_slug' => 'pickup',
                'fuel_type_slug' => 'diesel',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => '4wd',
                'exterior_color_slug' => 'candy-red',
                'interior_color_slug' => 'cabin-black',
                'price' => 1190000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(10),
                'sold_at' => null,
                'notes_internal' => 'Siêu bán tải Raptor phuộc FOX Live Valve, chạy giữ gìn không độ đẽo.',
            ],
            [
                'stock_code' => 'NEW-TERRITORY-001',
                'trim_slug' => 'territory-titanium-x',
                'condition' => 'new',
                'vin' => 'LVSCR9009SL000024',
                'year' => 2025,
                'mileage' => 15,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-black',
                'price' => 929000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(2),
                'sold_at' => null,
                'notes_internal' => 'Territory Titanium X mới 100%, sẵn xe giao ngay, tặng gói phụ kiện chính hãng.',
            ],

            // ================= 4. HYUNDAI (4 xe) =================
            [
                'stock_code' => 'NEW-SANTAFE-001',
                'trim_slug' => 'santafe-calligraphy-turbo',
                'condition' => 'new',
                'vin' => 'KMHSH1010SL000010',
                'year' => 2025,
                'mileage' => 20,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'awd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-brown',
                'price' => 1365000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(6),
                'sold_at' => null,
                'notes_internal' => 'Santa Fe thế hệ mới phong cách vuông vức, động cơ Turbo 281 mã lực.',
            ],
            [
                'stock_code' => 'USED-TUCSON-001',
                'trim_slug' => 'tucson-16-turbo',
                'condition' => 'used',
                'vin' => 'KMHJU1011SL000011',
                'year' => 2023,
                'mileage' => 26500,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'awd',
                'exterior_color_slug' => 'ocean-blue',
                'interior_color_slug' => 'cabin-black',
                'price' => 885000000,
                'currency' => 'VND',
                'status' => 'archived',
                'hold_until' => null,
                'published_at' => null,
                'sold_at' => null,
                'notes_internal' => 'Xe đã tạm rút khỏi sàn để bảo dưỡng tổng thể dàn lốp và sơn dặm bảo hiểm.',
            ],
            [
                'stock_code' => 'CPO-ACCENT-001',
                'trim_slug' => 'accent-15at',
                'condition' => 'cpo',
                'vin' => 'KMHHC1010SL000025',
                'year' => 2024,
                'mileage' => 10000,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-black',
                'price' => 535000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(8),
                'sold_at' => null,
                'notes_internal' => 'Accent bản Đặc Biệt thế hệ mới gói an toàn Hyundai SmartSense.',
            ],
            [
                'stock_code' => 'USED-SANTAFE-001',
                'trim_slug' => 'santafe-calligraphy-turbo',
                'condition' => 'used',
                'vin' => 'KMHSH1010SL000026',
                'year' => 2024,
                'mileage' => 18000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'awd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-brown',
                'price' => 1250000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(11),
                'sold_at' => null,
                'notes_internal' => 'Santa Fe Calligraphy lướt siêu đẹp, nội thất ghế cơ trưởng 6 chỗ.',
            ],

            // ================= 5. KIA (4 xe) =================
            [
                'stock_code' => 'USED-CARNIVAL-001',
                'trim_slug' => 'carnival-signature-7s',
                'condition' => 'used',
                'vin' => 'KNAKN1012SL000012',
                'year' => 2023,
                'mileage' => 34000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'diesel',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-brown',
                'price' => 1320000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(9),
                'sold_at' => null,
                'notes_internal' => 'Ghế VIP thương gia chỉnh điện, đệm đỡ bắp chân, cửa trượt điện thông minh.',
            ],
            [
                'stock_code' => 'CPO-SELTOS-001',
                'trim_slug' => 'seltos-gtline',
                'condition' => 'cpo',
                'vin' => 'KNAKN1012SL000027',
                'year' => 2024,
                'mileage' => 11000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'ocean-blue',
                'interior_color_slug' => 'cabin-black',
                'price' => 745000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(13),
                'sold_at' => null,
                'notes_internal' => 'Seltos GT-Line động cơ Turbo 158 mã lực, bảo dưỡng chính hãng.',
            ],
            [
                'stock_code' => 'NEW-CARNIVAL-001',
                'trim_slug' => 'carnival-signature-7s',
                'condition' => 'new',
                'vin' => 'KNAKN1012SL000028',
                'year' => 2025,
                'mileage' => 12,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'diesel',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-brown',
                'price' => 1439000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(2),
                'sold_at' => null,
                'notes_internal' => 'Carnival Signature 2025 bản 7 chỗ mới nhất, sẵn xe giao ngay.',
            ],
            [
                'stock_code' => 'NEW-SELTOS-001',
                'trim_slug' => 'seltos-gtline',
                'condition' => 'new',
                'vin' => 'KNAKN1012SL000029',
                'year' => 2025,
                'mileage' => 15,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'candy-red',
                'interior_color_slug' => 'cabin-black',
                'price' => 799000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(3),
                'sold_at' => null,
                'notes_internal' => 'Seltos 1.5 Turbo GT-Line xe mới, màn hình cong đôi 10.25 inch.',
            ],

            // ================= 6. MAZDA (4 xe) =================
            [
                'stock_code' => 'CPO-CX5-001',
                'trim_slug' => 'cx5-20-premium',
                'condition' => 'cpo',
                'vin' => 'JM1KF1013SL000013',
                'year' => 2024,
                'mileage' => 11500,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'candy-red',
                'interior_color_slug' => 'cabin-black',
                'price' => 815000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(10),
                'sold_at' => null,
                'notes_internal' => 'Màu đỏ pha lê Soul Red Crystal đặc trưng của Mazda, 10 loa Bose cao cấp.',
            ],
            [
                'stock_code' => 'DRAFT-MAZDA3-001',
                'trim_slug' => 'mazda3-premium-sport',
                'condition' => 'new',
                'vin' => 'JM1BP1018SL000018',
                'year' => 2025,
                'mileage' => 10,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'candy-red',
                'interior_color_slug' => 'cabin-black',
                'price' => 739000000,
                'currency' => 'VND',
                'status' => 'draft',
                'hold_until' => null,
                'published_at' => null,
                'sold_at' => null,
                'notes_internal' => 'Hồ sơ xe mới nhập kho đại lý, đang hoàn tất kiểm tra PDI và bộ ảnh chi tiết.',
            ],
            [
                'stock_code' => 'USED-CX5-001',
                'trim_slug' => 'cx5-20-premium',
                'condition' => 'used',
                'vin' => 'JM1KF1013SL000030',
                'year' => 2023,
                'mileage' => 29000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-black',
                'price' => 765000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(15),
                'sold_at' => null,
                'notes_internal' => 'CX-5 màu trắng ngọc trai gói trang bị an toàn cao cấp i-Activesense.',
            ],
            [
                'stock_code' => 'USED-MAZDA3-001',
                'trim_slug' => 'mazda3-premium-sport',
                'condition' => 'used',
                'vin' => 'JM1BP1018SL000031',
                'year' => 2023,
                'mileage' => 22000,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-black',
                'price' => 660000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(18),
                'sold_at' => null,
                'notes_internal' => 'Mazda 3 phom dáng thể thao kính hiển thị HUD trên kính lái.',
            ],

            // ================= 7. MERCEDES-BENZ (4 xe) =================
            [
                'stock_code' => 'NEW-C300-001',
                'trim_slug' => 'c300-amg',
                'condition' => 'new',
                'vin' => 'WDC201014SL000014',
                'year' => 2025,
                'mileage' => 18,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'rwd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-black',
                'price' => 2099000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(5),
                'sold_at' => null,
                'notes_internal' => 'Gói ngoại thất thể thao AMG Line, đèn pha Digital Light tối tân nhất.',
            ],
            [
                'stock_code' => 'NEW-GLC300-001',
                'trim_slug' => 'glc300-4matic',
                'condition' => 'new',
                'vin' => 'WDC251015SL000015',
                'year' => 2025,
                'mileage' => 12,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'awd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-brown',
                'price' => 2799000000,
                'currency' => 'VND',
                'status' => 'on_hold',
                'hold_until' => $now->copy()->addDays(3),
                'published_at' => $now->copy()->subDays(12),
                'sold_at' => null,
                'notes_internal' => 'Khách hàng VIP đã cọc giữ xe chờ ngày đẹp bấm biển số phong thủy.',
            ],
            [
                'stock_code' => 'CPO-C200-001',
                'trim_slug' => 'c200-avantgarde-plus',
                'condition' => 'cpo',
                'vin' => 'WDC201014SL000032',
                'year' => 2024,
                'mileage' => 14000,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'rwd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-brown',
                'price' => 1680000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(10),
                'sold_at' => null,
                'notes_internal' => 'Mercedes C 200 Avantgarde Plus nội thất da nâu âm thanh Burmester.',
            ],
            [
                'stock_code' => 'USED-GLC300-001',
                'trim_slug' => 'glc300-4matic',
                'condition' => 'used',
                'vin' => 'WDC251015SL000033',
                'year' => 2023,
                'mileage' => 25000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'awd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-black',
                'price' => 2450000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(17),
                'sold_at' => null,
                'notes_internal' => 'GLC 300 4MATIC lướt cực đẹp, lịch sử hãng chuẩn từng km.',
            ],

            // ================= 8. BMW (3 xe) =================
            [
                'stock_code' => 'CPO-BMW320-001',
                'trim_slug' => 'bmw-320i-m-sport',
                'condition' => 'cpo',
                'vin' => 'WBA311016SL000016',
                'year' => 2024,
                'mileage' => 13000,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'rwd',
                'exterior_color_slug' => 'ocean-blue',
                'interior_color_slug' => 'cabin-black',
                'price' => 1560000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(11),
                'sold_at' => null,
                'notes_internal' => 'Màu xanh Portimao Blue, gói M Sport khí động học, màn hình cong Curved Display.',
            ],
            [
                'stock_code' => 'NEW-BMW520-001',
                'trim_slug' => 'bmw-520i-m-sport',
                'condition' => 'new',
                'vin' => 'WBA511016SL000034',
                'year' => 2025,
                'mileage' => 15,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'rwd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-brown',
                'price' => 2399000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(4),
                'sold_at' => null,
                'notes_internal' => 'BMW Series 5 thế hệ mới đẳng cấp doanh nhân, âm thanh vòm Harman Kardon.',
            ],
            [
                'stock_code' => 'USED-BMW320-001',
                'trim_slug' => 'bmw-320i-m-sport',
                'condition' => 'used',
                'vin' => 'WBA311016SL000035',
                'year' => 2023,
                'mileage' => 27000,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'rwd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-black',
                'price' => 1450000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(20),
                'sold_at' => null,
                'notes_internal' => '320i M Sport màu trắng ngọc trai thể thao, cảm giác lái phấn khích.',
            ],

            // ================= 9. AUDI (2 xe) =================
            [
                'stock_code' => 'NEW-AUDIA6-001',
                'trim_slug' => 'audi-a6-45-tfsi',
                'condition' => 'new',
                'vin' => 'WAUA61016SL000036',
                'year' => 2025,
                'mileage' => 15,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'awd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-brown',
                'price' => 2450000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(6),
                'sold_at' => null,
                'notes_internal' => 'Audi A6 45 TFSI Quattro dẫn động 4 bánh toàn thời gian nhập khẩu Đức.',
            ],
            [
                'stock_code' => 'USED-AUDIA6-001',
                'trim_slug' => 'audi-a6-45-tfsi',
                'condition' => 'used',
                'vin' => 'WAUA61016SL000037',
                'year' => 2023,
                'mileage' => 21000,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'awd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-black',
                'price' => 2050000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(19),
                'sold_at' => null,
                'notes_internal' => 'Audi A6 lướt khoang lái kỹ thuật số Virtual Cockpit cực hiện đại.',
            ],

            // ================= 10. LEXUS (2 xe) =================
            [
                'stock_code' => 'NEW-LEXUSRX-001',
                'trim_slug' => 'lexus-rx350-premium',
                'condition' => 'new',
                'vin' => 'JTHRX1016SL000038',
                'year' => 2025,
                'mileage' => 10,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'awd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-brown',
                'price' => 3430000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(3),
                'sold_at' => null,
                'notes_internal' => 'Lexus RX 350 Premium thế hệ mới, sự êm ái và sang trọng hàng đầu Nhật Bản.',
            ],
            [
                'stock_code' => 'USED-LEXUSRX-001',
                'trim_slug' => 'lexus-rx350-premium',
                'condition' => 'used',
                'vin' => 'JTHRX1016SL000039',
                'year' => 2023,
                'mileage' => 17000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'awd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-beige',
                'price' => 3120000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(15),
                'sold_at' => null,
                'notes_internal' => 'Lexus RX 350 bảo dưỡng định kỳ chính hãng Lexus Thăng Long.',
            ],

            // ================= 11. PORSCHE (3 xe) =================
            [
                'stock_code' => 'USED-MACAN-001',
                'trim_slug' => 'porsche-macan-base',
                'condition' => 'used',
                'vin' => 'WP1AB1017SL000017',
                'year' => 2022,
                'mileage' => 31000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'awd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-black',
                'price' => 2850000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(15),
                'sold_at' => null,
                'notes_internal' => 'Full option chính hãng: Mâm 21 inch RS Spyder, gói Sport Chrono, ống xả thể thao.',
            ],
            [
                'stock_code' => 'CPO-MACAN-001',
                'trim_slug' => 'porsche-macan-base',
                'condition' => 'cpo',
                'vin' => 'WP1AB1017SL000040',
                'year' => 2024,
                'mileage' => 12000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'awd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-black',
                'price' => 3250000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(8),
                'sold_at' => null,
                'notes_internal' => 'Macan màu trắng ngọc trai gói nội thất da cao cấp đồng hồ Sport Chrono.',
            ],
            [
                'stock_code' => 'NEW-MACAN-001',
                'trim_slug' => 'porsche-macan-base',
                'condition' => 'new',
                'vin' => 'WP1AB1017SL000041',
                'year' => 2025,
                'mileage' => 10,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'awd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-brown',
                'price' => 3350000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(1),
                'sold_at' => null,
                'notes_internal' => 'Porsche Macan xe mới đập hộp, đặt hàng cá nhân hóa từ nhà máy Leipzig.',
            ],

            // ================= 12. PEUGEOT (1 xe) =================
            [
                'stock_code' => 'CPO-PEUGEOT-001',
                'trim_slug' => 'peugeot-3008-gt',
                'condition' => 'cpo',
                'vin' => 'VF3MC1017SL000042',
                'year' => 2024,
                'mileage' => 15000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'ocean-blue',
                'interior_color_slug' => 'cabin-black',
                'price' => 960000000,
                'currency' => 'VND',
                'status' => 'available',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(7),
                'sold_at' => null,
                'notes_internal' => 'Peugeot 3008 GT thiết kế i-Cockpit độc đáo của Pháp, nội thất da Alcantara.',
            ],

            // ================= 13. HISTORICAL SOLD UNITS (12 xe bổ sung để test lịch sử bán hàng & doanh thu) =================
            [
                'stock_code' => 'SOLD-CAMRY-001',
                'image_stock' => 'USED-CAMRY-001',
                'trim_slug' => 'camry-20q',
                'condition' => 'used',
                'vin' => 'JTNB11006SL000051',
                'year' => 2023,
                'mileage' => 28000,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-black',
                'price' => 1120000000,
                'currency' => 'VND',
                'status' => 'sold',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(60),
                'sold_at' => $now->copy()->subDays(32),
                'notes_internal' => 'Camry 2.0Q lướt biển Hà Nội, đã bàn giao cho khách hàng.',
            ],
            [
                'stock_code' => 'SOLD-VIOS-001',
                'image_stock' => 'CPO-VIOS-001',
                'trim_slug' => 'vios-e',
                'condition' => 'cpo',
                'vin' => 'RLVAB4004SL000052',
                'year' => 2024,
                'mileage' => 14000,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'cvt',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-beige',
                'price' => 480000000,
                'currency' => 'VND',
                'status' => 'sold',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(90),
                'sold_at' => $now->copy()->subDays(65),
                'notes_internal' => 'Vios E CVT chứng nhận chính hãng, đã hoàn tất thủ tục bàn giao.',
            ],
            [
                'stock_code' => 'SOLD-CIVIC-001',
                'image_stock' => 'USED-CIVIC-001',
                'trim_slug' => 'civic-rs',
                'condition' => 'used',
                'vin' => 'SHHFK1017SL000053',
                'year' => 2023,
                'mileage' => 21000,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'cvt',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'candy-red',
                'interior_color_slug' => 'cabin-black',
                'price' => 760000000,
                'currency' => 'VND',
                'status' => 'sold',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(80),
                'sold_at' => $now->copy()->subDays(45),
                'notes_internal' => 'Civic RS đỏ thể thao, đã ký hợp đồng chuyển nhượng trọn gói.',
            ],
            [
                'stock_code' => 'SOLD-CRV-001',
                'image_stock' => 'USED-CRV-001',
                'trim_slug' => 'crv-l-2wd',
                'condition' => 'used',
                'vin' => 'RLHRE1017SL000054',
                'year' => 2023,
                'mileage' => 31000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'cvt',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-black',
                'price' => 970000000,
                'currency' => 'VND',
                'status' => 'sold',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(110),
                'sold_at' => $now->copy()->subDays(85),
                'notes_internal' => 'CR-V bản L 1 cầu, full lịch sử hãng, đã hoàn tất giải ngân.',
            ],
            [
                'stock_code' => 'SOLD-EVEREST-001',
                'image_stock' => 'CPO-EVEREST-001',
                'trim_slug' => 'everest-titanium-plus',
                'condition' => 'cpo',
                'vin' => 'MNB2U1017SL000055',
                'year' => 2024,
                'mileage' => 11000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'diesel',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => '4wd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-brown',
                'price' => 1380000000,
                'currency' => 'VND',
                'status' => 'sold',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(60),
                'sold_at' => $now->copy()->subDays(40),
                'notes_internal' => 'Everest Titanium+ 2 cầu cao cấp, bàn giao xe kèm gói phụ kiện VIP.',
            ],
            [
                'stock_code' => 'SOLD-TERRITORY-001',
                'image_stock' => 'USED-TERRITORY-001',
                'trim_slug' => 'territory-titanium-x',
                'condition' => 'used',
                'vin' => 'VN1234017SL000056',
                'year' => 2023,
                'mileage' => 18500,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'ocean-blue',
                'interior_color_slug' => 'cabin-beige',
                'price' => 805000000,
                'currency' => 'VND',
                'status' => 'sold',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(70),
                'sold_at' => $now->copy()->subDays(48),
                'notes_internal' => 'Territory Titanium X đã sang tên đổi chủ, bảo hiểm thân vỏ 1 năm.',
            ],
            [
                'stock_code' => 'SOLD-SANTAFE-001',
                'image_stock' => 'USED-SANTAFE-001',
                'trim_slug' => 'santafe-calligraphy-turbo',
                'condition' => 'used',
                'vin' => 'KMHSH1017SL000057',
                'year' => 2024,
                'mileage' => 16000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'awd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-brown',
                'price' => 1240000000,
                'currency' => 'VND',
                'status' => 'sold',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(100),
                'sold_at' => $now->copy()->subDays(72),
                'notes_internal' => 'Santa Fe Calligraphy bản Turbo cao cấp, giao xe tại showroom.',
            ],
            [
                'stock_code' => 'SOLD-CARNIVAL-001',
                'image_stock' => 'USED-CARNIVAL-001',
                'trim_slug' => 'carnival-signature-7s',
                'condition' => 'used',
                'vin' => 'KNAFE1017SL000058',
                'year' => 2023,
                'mileage' => 26000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'diesel',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-brown',
                'price' => 1290000000,
                'currency' => 'VND',
                'status' => 'sold',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(120),
                'sold_at' => $now->copy()->subDays(95),
                'notes_internal' => 'Carnival Signature 7 chỗ phục vụ doanh nghiệp, hoàn tất hợp đồng công chứng.',
            ],
            [
                'stock_code' => 'SOLD-CX5-001',
                'image_stock' => 'CPO-CX5-001',
                'trim_slug' => 'cx5-20-premium',
                'condition' => 'cpo',
                'vin' => 'JMZKF1017SL000059',
                'year' => 2024,
                'mileage' => 9500,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'fwd',
                'exterior_color_slug' => 'candy-red',
                'interior_color_slug' => 'cabin-black',
                'price' => 810000000,
                'currency' => 'VND',
                'status' => 'sold',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(25),
                'sold_at' => $now->copy()->subDays(10),
                'notes_internal' => 'CX-5 màu đỏ pha lê Soul Red Crystal, bảo hành chính hãng Thaco.',
            ],
            [
                'stock_code' => 'SOLD-C300-001',
                'image_stock' => 'NEW-C300-001',
                'trim_slug' => 'c300-amg',
                'condition' => 'cpo',
                'vin' => 'WDD201017SL000060',
                'year' => 2024,
                'mileage' => 8200,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'rwd',
                'exterior_color_slug' => 'obsidian-black',
                'interior_color_slug' => 'cabin-brown',
                'price' => 1990000000,
                'currency' => 'VND',
                'status' => 'sold',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(15),
                'sold_at' => $now->copy()->subHours(4),
                'notes_internal' => 'Mercedes C300 AMG xe chạy lướt cực đẹp, bàn giao hoa tươi chúc mừng khách hàng.',
            ],
            [
                'stock_code' => 'SOLD-BMW320-001',
                'image_stock' => 'CPO-BMW320-001',
                'trim_slug' => 'bmw-320i-m-sport',
                'condition' => 'used',
                'vin' => 'WBA5R1017SL000061',
                'year' => 2023,
                'mileage' => 22000,
                'body_type_slug' => 'sedan',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'rwd',
                'exterior_color_slug' => 'ocean-blue',
                'interior_color_slug' => 'cabin-black',
                'price' => 1430000000,
                'currency' => 'VND',
                'status' => 'sold',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(130),
                'sold_at' => $now->copy()->subDays(110),
                'notes_internal' => 'BMW 320i M Sport xanh Portimao Blue, giao dịch chốt nhanh gọn.',
            ],
            [
                'stock_code' => 'SOLD-LEXUSRX-001',
                'image_stock' => 'USED-LEXUSRX-001',
                'trim_slug' => 'lexus-rx350-premium',
                'condition' => 'used',
                'vin' => 'JTJBC1017SL000062',
                'year' => 2023,
                'mileage' => 19000,
                'body_type_slug' => 'suv',
                'fuel_type_slug' => 'gasoline',
                'transmission_slug' => 'automatic',
                'drivetrain_slug' => 'awd',
                'exterior_color_slug' => 'pearl-white',
                'interior_color_slug' => 'cabin-brown',
                'price' => 3150000000,
                'currency' => 'VND',
                'status' => 'sold',
                'hold_until' => null,
                'published_at' => $now->copy()->subDays(150),
                'sold_at' => $now->copy()->subDays(125),
                'notes_internal' => 'Lexus RX350 Luxury nhập khẩu nguyên chiếc, khách hàng VIP showroom.',
            ],
        ];

        $seededStockCodes = array_column($units, 'stock_code');
        $unseededIds = DB::table('car_units')->whereNotIn('stock_code', $seededStockCodes)->pluck('id');
        if ($unseededIds->isNotEmpty()) {
            DB::table('car_unit_media')->whereIn('car_unit_id', $unseededIds)->delete();
            DB::table('car_unit_holds')->whereIn('car_unit_id', $unseededIds)->delete();
            DB::table('car_unit_price_histories')->whereIn('car_unit_id', $unseededIds)->delete();
            DB::table('car_units')->whereIn('id', $unseededIds)->delete();
        }

        foreach ($units as $unit) {
            DB::table('car_units')->updateOrInsert(
                ['stock_code' => $unit['stock_code']],
                [
                    'trim_id' => $trimIds[$unit['trim_slug']],
                    'condition' => $unit['condition'],
                    'vin' => $unit['vin'],
                    'year' => $unit['year'],
                    'mileage' => $unit['mileage'],
                    'body_type_id' => $bodyTypeIds[$unit['body_type_slug']],
                    'fuel_type_id' => $fuelTypeIds[$unit['fuel_type_slug']],
                    'transmission_id' => $transmissionIds[$unit['transmission_slug']],
                    'drivetrain_id' => $drivetrainIds[$unit['drivetrain_slug']],
                    'exterior_color_id' => $colorIds[$unit['exterior_color_slug']],
                    'interior_color_id' => $colorIds[$unit['interior_color_slug']],
                    'price' => $unit['price'],
                    'currency' => $unit['currency'],
                    'status' => $unit['status'],
                    'hold_until' => $unit['hold_until'],
                    'published_at' => $unit['published_at'],
                    'sold_at' => $unit['sold_at'],
                    'notes_internal' => $unit['notes_internal'],
                    'deleted_at' => null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
        }

        $unitIds = DB::table('car_units')
            ->whereIn('stock_code', array_column($units, 'stock_code'))
            ->pluck('id', 'stock_code');

        DB::table('car_unit_media')->delete();
        $mediaRows = [];

        foreach ($units as $unit) {
            $stock = $unit['stock_code'];
            $imageStock = $unit['image_stock'] ?? $stock;
            // 3 uniform 16:9 images per car
            $mediaRows[] = [
                'stock_code' => $stock,
                'type' => 'image',
                'path_or_url' => "/seed-media/cars/{$imageStock}_1.jpg",
                'caption' => 'Góc chụp ngoại thất 3/4 trước',
                'sort_order' => 1,
                'is_cover' => true,
            ];
            $mediaRows[] = [
                'stock_code' => $stock,
                'type' => 'image',
                'path_or_url' => "/seed-media/cars/{$imageStock}_2.jpg",
                'caption' => 'Góc chụp thân và đuôi xe',
                'sort_order' => 2,
                'is_cover' => false,
            ];
            $mediaRows[] = [
                'stock_code' => $stock,
                'type' => 'image',
                'path_or_url' => "/seed-media/cars/{$imageStock}_3.jpg",
                'caption' => 'Khoang lái và bảng điều khiển taplo',
                'sort_order' => 3,
                'is_cover' => false,
            ];
        }

        foreach ($mediaRows as $media) {
            if (! isset($unitIds[$media['stock_code']])) {
                continue;
            }

            DB::table('car_unit_media')->insert([
                'car_unit_id' => $unitIds[$media['stock_code']],
                'type' => $media['type'],
                'path_or_url' => $media['path_or_url'],
                'caption' => $media['caption'],
                'sort_order' => $media['sort_order'],
                'is_cover' => $media['is_cover'],
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }

        $staffId = DB::table('users')->where('email', 'staff@showroom.test')->value('id');

        DB::table('car_unit_holds')->delete();
        $holds = [
            [
                'stock_code' => 'USED-CROSS-001',
                'hold_until' => $now->copy()->addDays(2),
                'reason' => 'Đang chờ hồ sơ vay mua xe từ ngân hàng phê duyệt.',
            ],
            [
                'stock_code' => 'NEW-GLC300-001',
                'hold_until' => $now->copy()->addDays(3),
                'reason' => 'Khách hàng VIP cọc giữ xe chờ ngày đẹp nhận xe.',
            ],
        ];

        foreach ($holds as $hold) {
            if (isset($unitIds[$hold['stock_code']])) {
                DB::table('car_unit_holds')->insert([
                    'car_unit_id' => $unitIds[$hold['stock_code']],
                    'created_by' => $staffId,
                    'hold_until' => $hold['hold_until'],
                    'reason' => $hold['reason'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }
        }

        DB::table('car_unit_price_histories')->delete();
        $priceHistories = [
            [
                'stock_code' => 'NEW-CIVIC-001',
                'old_price' => 879000000,
                'new_price' => 865000000,
                'days_ago' => 2,
            ],
            [
                'stock_code' => 'USED-CROSS-001',
                'old_price' => 845000000,
                'new_price' => 825000000,
                'days_ago' => 6,
            ],
            [
                'stock_code' => 'USED-RANGER-001',
                'old_price' => 945000000,
                'new_price' => 920000000,
                'days_ago' => 10,
            ],
            [
                'stock_code' => 'CPO-EVEREST-001',
                'old_price' => 1420000000,
                'new_price' => 1390000000,
                'days_ago' => 4,
            ],
            [
                'stock_code' => 'USED-MACAN-001',
                'old_price' => 2920000000,
                'new_price' => 2850000000,
                'days_ago' => 8,
            ],
            [
                'stock_code' => 'NEW-CAMRY-001',
                'old_price' => 1520000000,
                'new_price' => 1495000000,
                'days_ago' => 3,
            ],
            [
                'stock_code' => 'NEW-C300-001',
                'old_price' => 2150000000,
                'new_price' => 2099000000,
                'days_ago' => 5,
            ],
        ];

        foreach ($priceHistories as $ph) {
            if (isset($unitIds[$ph['stock_code']])) {
                DB::table('car_unit_price_histories')->insert([
                    'car_unit_id' => $unitIds[$ph['stock_code']],
                    'changed_by' => $staffId,
                    'old_price' => $ph['old_price'],
                    'new_price' => $ph['new_price'],
                    'created_at' => $now->copy()->subDays($ph['days_ago']),
                    'updated_at' => $now->copy()->subDays($ph['days_ago']),
                ]);
            }
        }
    }
}
